version: '3.8'

services:
  notification-db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - notification_data:/var/lib/postgresql/data/

  notification-service:
    build: .
    ports:
      - "8005:8000"
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - notification-db

  celery-worker:
    build: .
    command: celery -A notifications worker --loglevel=info
    env_file: .env
    depends_on:
      - notification-service
      - notification-db

volumes:
  notification_data: