version: '3.8'

services:
  ticket-db:
    image: postgres:13
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ticket_data:/var/lib/postgresql/data/

  ticket-service:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env 
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BILLBOARD_SERVICE_URL: ${BILLBOARD_SERVICE_URL}
    depends_on:
      - ticket-db

volumes:
  ticket_data: