services:
  food-db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - food_data:/var/lib/postgresql/data/

  food-service:
    build: .
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    depends_on:
      - food-db

volumes:
  food_data: