version: '3.8'

services:
  payment-db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - payment_data:/var/lib/postgresql/data/

  payment-service:
    build: .
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      TICKET_SERVICE_URL: ${TICKET_SERVICE_URL}
    depends_on:
      - payment-db
      - user-service
      - ticket-service

volumes:
  payment_data: