version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - user_data:/var/lib/postgresql/data/

  app:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env 
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    depends_on:
      - db
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  user_data: