version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - user_data:/var/lib/postgresql/data/

  app:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env 
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
        - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  user_data: